============================= test session starts ==============================
platform darwin -- Python 3.13.3, pytest-8.4.2, pluggy-1.6.0
rootdir: /Users/junlim/Purdue/fall2025/ECE30861/ece30861-team9
plugins: cov-7.0.0
collected 22 items

tests/test_classify.py ........                                          [ 36%]
tests/test_hf_id.py .F

=================================== FAILURES ===================================
_ test_hf_id_good[https://huggingface.co/google/gemma-3-270m/tree/main-google/gemma-3-270m] _

u = 'https://huggingface.co/google/gemma-3-270m/tree/main'
expect = 'google/gemma-3-270m'

    @pytest.mark.parametrize("u,expect", [
        ("https://huggingface.co/google/gemma-3-270m", "google/gemma-3-270m"),
        ("https://huggingface.co/google/gemma-3-270m/tree/main", "google/gemma-3-270m"),
        ("google/gemma-3-270m", "google/gemma-3-270m"),
        (" hf://google/gemma-3-270m ", "google/gemma-3-270m"),
    ])
    def test_hf_id_good(u, expect):
>       assert _hf_model_id_from_url(u) == expect
E       AssertionError: assert 'google/gemma...70m/tree/main' == 'google/gemma-3-270m'
E         
E         - google/gemma-3-270m
E         + google/gemma-3-270m/tree/main
E         ?                    ++++++++++

tests/test_hf_id.py:11: AssertionError
=========================== short test summary info ============================
FAILED tests/test_hf_id.py::test_hf_id_good[https://huggingface.co/google/gemma-3-270m/tree/main-google/gemma-3-270m]
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
========================= 1 failed, 9 passed in 0.03s ==========================
